language: c
compiler:
- gcc
install:
# valac, gpsd, libudev
- sudo add-apt-repository -y ppa:vala-team/ppa
- sudo apt-get -qq update
- sudo apt-get -qq install valac libglib2.0-dev libgps-dev libudev-dev
# LCM binary (precompiled by me)
- wget $CI_BINARIES_PATH/$LCM_DEB
- sudo dpkg -i $LCM_DEB
# MAVLink headers (packaged c_library repo)
- wget $CI_BINARIES_PATH/$MAVLINK_DEB
- sudo dpkg -i $MAVLINK_DEB
script:
- cmake .
- make VERBOSE=1
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2f6114466e43864c1481
    on_success: change
    on_failure: always
    on_start: false
