language: cpp
compiler:
- gcc
install:
# GCC 4.8 for proper C++11
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
- sudo apt-get -qq install g++-4.8
- export CXX="g++-4.8" CC="gcc-4.8"
# LCM binary (precompiled by me)
- wget $CI_BINARIES_PATH/$LCM_DEB
- sudo dpkg -i $LCM_DEB
# MAVLink headers (packaged c_library repo)
- wget $CI_BINARIES_PATH/$MAVLINK_DEB
- sudo dpkg -i $MAVLINK_DEB
# console-bridge
- sudo apt-get -qq install libboost-all-dev
- git clone --depth 1 https://github.com/ros/console_bridge.git
- cd console_bridge && cmake . && make
- sudo make install
- cd ..
# gpsd and libudev
- sudo apt-get -qq install libgps-dev libudev-dev
# valac
- sudo add-apt-repository -y ppa:vala-team/ppa
- sudo apt-get -qq update
- sudo apt-get -qq install valac libglib2.0-dev
script:
- mkdir -p build
- cd build && cmake ..
- make VERBOSE=1
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2f6114466e43864c1481
    on_success: change
    on_failure: always
    on_start: false
