/* test.c generated by valac 0.24.0, the Vala compiler
 * generated from test.vala, do not modify */

/* test lcm.vala
 * valac --vapidir ./vapi --pkg lcm -C test.vala
 */

#include <glib.h>
#include <glib-object.h>
#include <lcm.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define _lcm_subscription_unref0(var) ((var == NULL) ? NULL : (var = (lcm_subscription_unref (var), NULL)))
#define _lcm_destroy0(var) ((var == NULL) ? NULL : (var = (lcm_destroy (var), NULL)))



void topic_cb (lcm_recv_buf_t* rbuf, const gchar* channel, void* user_data);
gint _vala_main (gchar** args, int args_length1);
static void _topic_cb_lcm_msg_handler_t (lcm_recv_buf_t* rbuf, const gchar* channel, void* user_data);


void topic_cb (lcm_recv_buf_t* rbuf, const gchar* channel, void* user_data) {
	FILE* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	lcm_recv_buf_t _tmp2_ = {0};
	guint32 _tmp3_ = 0U;
	g_return_if_fail (rbuf != NULL);
	g_return_if_fail (channel != NULL);
	_tmp0_ = stdout;
	_tmp1_ = channel;
	_tmp2_ = *rbuf;
	_tmp3_ = _tmp2_.data_size;
	fprintf (_tmp0_, "got message from %s channel, size %u bytes\n", _tmp1_, (guint) _tmp3_);
}


static void _topic_cb_lcm_msg_handler_t (lcm_recv_buf_t* rbuf, const gchar* channel, void* user_data) {
	topic_cb (rbuf, channel, user_data);
}


static gpointer _lcm_subscription_ref0 (gpointer self) {
	return self ? lcm_subscription_ref (self) : NULL;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	gint64* testdatamesg = NULL;
	gint64* _tmp0_ = NULL;
	gint testdatamesg_length1 = 0;
	gint _testdatamesg_size_ = 0;
	lcm_t* lcm = NULL;
	lcm_t* _tmp1_ = NULL;
	gint fn = 0;
	gint _tmp2_ = 0;
	FILE* _tmp3_ = NULL;
	lcm_subscription_t* sub = NULL;
	lcm_subscription_t* _tmp4_ = NULL;
	lcm_subscription_t* _tmp5_ = NULL;
	FILE* _tmp6_ = NULL;
	FILE* _tmp7_ = NULL;
	_tmp0_ = g_new0 (gint64, 5);
	_tmp0_[0] = 0xd00dfeedLL;
	_tmp0_[1] = 0xdeeadbeefLL;
	_tmp0_[2] = 0xeeeeeeeeLL;
	_tmp0_[3] = 0xffff0000LL;
	_tmp0_[4] = (gint64) 0x5a5aa5a5;
	testdatamesg = _tmp0_;
	testdatamesg_length1 = 5;
	_testdatamesg_size_ = testdatamesg_length1;
	_tmp1_ = lcm_create (NULL);
	lcm = _tmp1_;
	_tmp2_ = lcm_get_fileno (lcm);
	fn = _tmp2_;
	_tmp3_ = stdout;
	fprintf (_tmp3_, "lcm fileno: %d\n", fn);
	_tmp4_ = lcm_subscribe (lcm, "test_topic\n", _topic_cb_lcm_msg_handler_t, NULL);
	_tmp5_ = _lcm_subscription_ref0 (_tmp4_);
	sub = _tmp5_;
	_tmp6_ = stdout;
	fprintf (_tmp6_, "try to publish message\n");
	lcm_publish (lcm, "test_topic", (void*) testdatamesg, (testdatamesg_length1 * sizeof (gint64)) / sizeof (void));
	_tmp7_ = stdout;
	fprintf (_tmp7_, "handle\n");
	lcm_handle (lcm);
	lcm_publish (lcm, "test_topic", (void*) testdatamesg, (testdatamesg_length1 * sizeof (gint64)) / sizeof (void));
	lcm_handle_timeout (lcm, 1000);
	lcm_unsubscribe (lcm, sub);
	result = 0;
	_lcm_subscription_unref0 (sub);
	_lcm_destroy0 (lcm);
	testdatamesg = (g_free (testdatamesg), NULL);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



